name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    # branches:
    # branches-ignore:
    #  - master
    #  - alpha

jobs:
  build-test:
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@4fbb5a02fac424d5059494d03d2871eba7605189
