name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    # branches:
    # branches-ignore:
    #  - master
    #  - alpha

jobs:
  build-test:
    name: Lint and Test
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@6da3b9300d3cc7d7cfb1108c7f5b3783b2a18826
    with:
      job-title: Lint and Test
      pnpm-commands: '[ "lint", "test" ]'
      os: '["ubuntu-latest"]'
